In [2]:
run run_cold+hot_f475w_Nie_20210103.py

Running cold
Running hot
Read cold and hot catalogs
['NUMBER', 'FLUX_ISO', 'FLUXERR_ISO', 'MAG_ISO', 'MAGERR_ISO', 'FLUX_AUTO', 'FLUXERR_AUTO', 'MAG_AUTO', 'MAGERR_AUTO', 'MAG_BEST', 'MAGERR_BEST', 'KRON_RADIUS', 'BACKGROUND', 'X_IMAGE', 'Y_IMAGE', 'ALPHA_J2000', 'DELTA_J2000', 'CXX_IMAGE', 'CYY_IMAGE', 'CXY_IMAGE', 'ELLIPTICITY', 'FWHM_IMAGE', 'FLUX_RADIUS', 'FLAGS', 'CLASS_STAR', 'A_IMAGE', 'B_IMAGE', 'XMIN_IMAGE', 'YMIN_IMAGE', 'XMAX_IMAGE', 'YMAX_IMAGE', 'ELONGATION', 'THETA_IMAGE', 'ISOAREA_IMAGE']
Including hot detections
('N:', 8, 0, 1599)
('N:', 8, 1, 1598)
('N:', 8, 2, 1596)
('N:', 8, 3, 1596)
('N:', 8, 4, 1587)
('N:', 8, 5, 1587)
('N:', 8, 6, 1586)
('N:', 8, 7, 1583)
1583
Creating combined segmentation map
(1583, 0)
(1583, 1)
(1583, 2)
(1583, 3)
(1583, 4)
(1583, 5)
(1583, 6)
(1583, 7)
(1583, 8)
(1583, 9)
(1583, 10)
(1583, 11)
(1583, 12)
(1583, 13)
(1583, 14)
(1583, 15)
(1583, 16)
(1583, 17)
(1583, 18)
(1583, 19)
(1583, 20)
(1583, 21)
(1583, 22)
(1583, 23)
(1583, 24)
(1583, 25

(1583, 675)
(1583, 676)
(1583, 677)
(1583, 678)
(1583, 679)
(1583, 680)
(1583, 681)
(1583, 682)
(1583, 683)
(1583, 684)
(1583, 685)
(1583, 686)
(1583, 687)
(1583, 688)
(1583, 689)
(1583, 690)
(1583, 691)
(1583, 692)
(1583, 693)
(1583, 694)
(1583, 695)
(1583, 696)
(1583, 697)
(1583, 698)
(1583, 699)
(1583, 700)
(1583, 701)
(1583, 702)
(1583, 703)
(1583, 704)
(1583, 705)
(1583, 706)
(1583, 707)
(1583, 708)
(1583, 709)
(1583, 710)
(1583, 711)
(1583, 712)
(1583, 713)
(1583, 714)
(1583, 715)
(1583, 716)
(1583, 717)
(1583, 718)
(1583, 719)
(1583, 720)
(1583, 721)
(1583, 722)
(1583, 723)
(1583, 724)
(1583, 725)
(1583, 726)
(1583, 727)
(1583, 728)
(1583, 729)
(1583, 730)
(1583, 731)
(1583, 732)
(1583, 733)
(1583, 734)
(1583, 735)
(1583, 736)
(1583, 737)
(1583, 738)
(1583, 739)
(1583, 740)
(1583, 741)
(1583, 742)
(1583, 743)
(1583, 744)
(1583, 745)
(1583, 746)
(1583, 747)
(1583, 748)
(1583, 749)
(1583, 750)
(1583, 751)
(1583, 752)
(1583, 753)
(1583, 754)
(1583, 755)
(1583, 756)
(1583, 757)
(158

(1583, 1359)
(1583, 1360)
(1583, 1361)
(1583, 1362)
(1583, 1363)
(1583, 1364)
(1583, 1365)
(1583, 1366)
(1583, 1367)
(1583, 1368)
(1583, 1369)
(1583, 1370)
(1583, 1371)
(1583, 1372)
(1583, 1373)
(1583, 1374)
(1583, 1375)
(1583, 1376)
(1583, 1377)
(1583, 1378)
(1583, 1379)
(1583, 1380)
(1583, 1381)
(1583, 1382)
(1583, 1383)
(1583, 1384)
(1583, 1385)
(1583, 1386)
(1583, 1387)
(1583, 1388)
(1583, 1389)
(1583, 1390)
(1583, 1391)
(1583, 1392)
(1583, 1393)
(1583, 1394)
(1583, 1395)
(1583, 1396)
(1583, 1397)
(1583, 1398)
(1583, 1399)
(1583, 1400)
(1583, 1401)
(1583, 1402)
(1583, 1403)
(1583, 1404)
(1583, 1405)
(1583, 1406)
(1583, 1407)
(1583, 1408)
(1583, 1409)
(1583, 1410)
(1583, 1411)
(1583, 1412)
(1583, 1413)
(1583, 1414)
(1583, 1415)
(1583, 1416)
(1583, 1417)
(1583, 1418)
(1583, 1419)
(1583, 1420)
(1583, 1421)
(1583, 1422)
(1583, 1423)
(1583, 1424)
(1583, 1425)
(1583, 1426)
(1583, 1427)
(1583, 1428)
(1583, 1429)
(1583, 1430)
(1583, 1431)
(1583, 1432)
(1583, 1433)
(1583, 1434)
(1583, 1435)

(2316, 232)
(2316, 233)
(2316, 234)
(2316, 235)
(2316, 236)
(2316, 237)
(2316, 238)
(2316, 239)
(2316, 240)
(2316, 241)
(2316, 242)
(2316, 243)
(2316, 244)
(2316, 245)
(2316, 246)
(2316, 247)
(2316, 248)
(2316, 249)
(2316, 250)
(2316, 251)
(2316, 252)
(2316, 253)
(2316, 254)
(2316, 255)
(2316, 256)
(2316, 257)
(2316, 258)
(2316, 259)
(2316, 260)
(2316, 261)
(2316, 262)
(2316, 263)
(2316, 264)
(2316, 265)
(2316, 266)
(2316, 267)
(2316, 268)
(2316, 269)
(2316, 270)
(2316, 271)
(2316, 272)
(2316, 273)
(2316, 274)
(2316, 275)
(2316, 276)
(2316, 277)
(2316, 278)
(2316, 279)
(2316, 280)
(2316, 281)
(2316, 282)
(2316, 283)
(2316, 284)
(2316, 285)
(2316, 286)
(2316, 287)
(2316, 288)
(2316, 289)
(2316, 290)
(2316, 291)
(2316, 292)
(2316, 293)
(2316, 294)
(2316, 295)
(2316, 296)
(2316, 297)
(2316, 298)
(2316, 299)
(2316, 300)
(2316, 301)
(2316, 302)
(2316, 303)
(2316, 304)
(2316, 305)
(2316, 306)
(2316, 307)
(2316, 308)
(2316, 309)
(2316, 310)
(2316, 311)
(2316, 312)
(2316, 313)
(2316, 314)
(231

(2316, 920)
(2316, 921)
(2316, 922)
(2316, 923)
(2316, 924)
(2316, 925)
(2316, 926)
(2316, 927)
(2316, 928)
(2316, 929)
(2316, 930)
(2316, 931)
(2316, 932)
(2316, 933)
(2316, 934)
(2316, 935)
(2316, 936)
(2316, 937)
(2316, 938)
(2316, 939)
(2316, 940)
(2316, 941)
(2316, 942)
(2316, 943)
(2316, 944)
(2316, 945)
(2316, 946)
(2316, 947)
(2316, 948)
(2316, 949)
(2316, 950)
(2316, 951)
(2316, 952)
(2316, 953)
(2316, 954)
(2316, 955)
(2316, 956)
(2316, 957)
(2316, 958)
(2316, 959)
(2316, 960)
(2316, 961)
(2316, 962)
(2316, 963)
(2316, 964)
(2316, 965)
(2316, 966)
(2316, 967)
(2316, 968)
(2316, 969)
(2316, 970)
(2316, 971)
(2316, 972)
(2316, 973)
(2316, 974)
(2316, 975)
(2316, 976)
(2316, 977)
(2316, 978)
(2316, 979)
(2316, 980)
(2316, 981)
(2316, 982)
(2316, 983)
(2316, 984)
(2316, 985)
(2316, 986)
(2316, 987)
(2316, 988)
(2316, 989)
(2316, 990)
(2316, 991)
(2316, 992)
(2316, 993)
(2316, 994)
(2316, 995)
(2316, 996)
(2316, 997)
(2316, 998)
(2316, 999)
(2316, 1000)
(2316, 1001)
(2316, 1002)
(

(2316, 1597)
(2316, 1598)
(2316, 1599)
(2316, 1600)
(2316, 1601)
(2316, 1602)
(2316, 1603)
(2316, 1604)
(2316, 1605)
(2316, 1606)
(2316, 1607)
(2316, 1608)
(2316, 1609)
(2316, 1610)
(2316, 1611)
(2316, 1612)
(2316, 1613)
(2316, 1614)
(2316, 1615)
(2316, 1616)
(2316, 1617)
(2316, 1618)
(2316, 1619)
(2316, 1620)
(2316, 1621)
(2316, 1622)
(2316, 1623)
(2316, 1624)
(2316, 1625)
(2316, 1626)
(2316, 1627)
(2316, 1628)
(2316, 1629)
(2316, 1630)
(2316, 1631)
(2316, 1632)
(2316, 1633)
(2316, 1634)
(2316, 1635)
(2316, 1636)
(2316, 1637)
(2316, 1638)
(2316, 1639)
(2316, 1640)
(2316, 1641)
(2316, 1642)
(2316, 1643)
(2316, 1644)
(2316, 1645)
(2316, 1646)
(2316, 1647)
(2316, 1648)
(2316, 1649)
(2316, 1650)
(2316, 1651)
(2316, 1652)
(2316, 1653)
(2316, 1654)
(2316, 1655)
(2316, 1656)
(2316, 1657)
(2316, 1658)
(2316, 1659)
(2316, 1660)
(2316, 1661)
(2316, 1662)
(2316, 1663)
(2316, 1664)
(2316, 1665)
(2316, 1666)
(2316, 1667)
(2316, 1668)
(2316, 1669)
(2316, 1670)
(2316, 1671)
(2316, 1672)
(2316, 1673)

(2316, 2242)
(2316, 2243)
(2316, 2244)
(2316, 2245)
(2316, 2246)
(2316, 2247)
(2316, 2248)
(2316, 2249)
(2316, 2250)
(2316, 2251)
(2316, 2252)
(2316, 2253)
(2316, 2254)
(2316, 2255)
(2316, 2256)
(2316, 2257)
(2316, 2258)
(2316, 2259)
(2316, 2260)
(2316, 2261)
(2316, 2262)
(2316, 2263)
(2316, 2264)
(2316, 2265)
(2316, 2266)
(2316, 2267)
(2316, 2268)
(2316, 2269)
(2316, 2270)
(2316, 2271)
(2316, 2272)
(2316, 2273)
(2316, 2274)
(2316, 2275)
(2316, 2276)
(2316, 2277)
(2316, 2278)
(2316, 2279)
(2316, 2280)
(2316, 2281)
(2316, 2282)
(2316, 2283)
(2316, 2284)
(2316, 2285)
(2316, 2286)
(2316, 2287)
(2316, 2288)
(2316, 2289)
(2316, 2290)
(2316, 2291)
(2316, 2292)
(2316, 2293)
(2316, 2294)
(2316, 2295)
(2316, 2296)
(2316, 2297)
(2316, 2298)
(2316, 2299)
(2316, 2300)
(2316, 2301)
(2316, 2302)
(2316, 2303)
(2316, 2304)
(2316, 2305)
(2316, 2306)
(2316, 2307)
(2316, 2308)
(2316, 2309)
(2316, 2310)
(2316, 2311)
(2316, 2312)
(2316, 2313)
(2316, 2314)
(2316, 2315)
Running cold
Running hot
Read cold and

(2370, 437)
(2370, 438)
(2370, 439)
(2370, 440)
(2370, 441)
(2370, 442)
(2370, 443)
(2370, 444)
(2370, 445)
(2370, 446)
(2370, 447)
(2370, 448)
(2370, 449)
(2370, 450)
(2370, 451)
(2370, 452)
(2370, 453)
(2370, 454)
(2370, 455)
(2370, 456)
(2370, 457)
(2370, 458)
(2370, 459)
(2370, 460)
(2370, 461)
(2370, 462)
(2370, 463)
(2370, 464)
(2370, 465)
(2370, 466)
(2370, 467)
(2370, 468)
(2370, 469)
(2370, 470)
(2370, 471)
(2370, 472)
(2370, 473)
(2370, 474)
(2370, 475)
(2370, 476)
(2370, 477)
(2370, 478)
(2370, 479)
(2370, 480)
(2370, 481)
(2370, 482)
(2370, 483)
(2370, 484)
(2370, 485)
(2370, 486)
(2370, 487)
(2370, 488)
(2370, 489)
(2370, 490)
(2370, 491)
(2370, 492)
(2370, 493)
(2370, 494)
(2370, 495)
(2370, 496)
(2370, 497)
(2370, 498)
(2370, 499)
(2370, 500)
(2370, 501)
(2370, 502)
(2370, 503)
(2370, 504)
(2370, 505)
(2370, 506)
(2370, 507)
(2370, 508)
(2370, 509)
(2370, 510)
(2370, 511)
(2370, 512)
(2370, 513)
(2370, 514)
(2370, 515)
(2370, 516)
(2370, 517)
(2370, 518)
(2370, 519)
(237

(2370, 1151)
(2370, 1152)
(2370, 1153)
(2370, 1154)
(2370, 1155)
(2370, 1156)
(2370, 1157)
(2370, 1158)
(2370, 1159)
(2370, 1160)
(2370, 1161)
(2370, 1162)
(2370, 1163)
(2370, 1164)
(2370, 1165)
(2370, 1166)
(2370, 1167)
(2370, 1168)
(2370, 1169)
(2370, 1170)
(2370, 1171)
(2370, 1172)
(2370, 1173)
(2370, 1174)
(2370, 1175)
(2370, 1176)
(2370, 1177)
(2370, 1178)
(2370, 1179)
(2370, 1180)
(2370, 1181)
(2370, 1182)
(2370, 1183)
(2370, 1184)
(2370, 1185)
(2370, 1186)
(2370, 1187)
(2370, 1188)
(2370, 1189)
(2370, 1190)
(2370, 1191)
(2370, 1192)
(2370, 1193)
(2370, 1194)
(2370, 1195)
(2370, 1196)
(2370, 1197)
(2370, 1198)
(2370, 1199)
(2370, 1200)
(2370, 1201)
(2370, 1202)
(2370, 1203)
(2370, 1204)
(2370, 1205)
(2370, 1206)
(2370, 1207)
(2370, 1208)
(2370, 1209)
(2370, 1210)
(2370, 1211)
(2370, 1212)
(2370, 1213)
(2370, 1214)
(2370, 1215)
(2370, 1216)
(2370, 1217)
(2370, 1218)
(2370, 1219)
(2370, 1220)
(2370, 1221)
(2370, 1222)
(2370, 1223)
(2370, 1224)
(2370, 1225)
(2370, 1226)
(2370, 1227)

(2370, 1791)
(2370, 1792)
(2370, 1793)
(2370, 1794)
(2370, 1795)
(2370, 1796)
(2370, 1797)
(2370, 1798)
(2370, 1799)
(2370, 1800)
(2370, 1801)
(2370, 1802)
(2370, 1803)
(2370, 1804)
(2370, 1805)
(2370, 1806)
(2370, 1807)
(2370, 1808)
(2370, 1809)
(2370, 1810)
(2370, 1811)
(2370, 1812)
(2370, 1813)
(2370, 1814)
(2370, 1815)
(2370, 1816)
(2370, 1817)
(2370, 1818)
(2370, 1819)
(2370, 1820)
(2370, 1821)
(2370, 1822)
(2370, 1823)
(2370, 1824)
(2370, 1825)
(2370, 1826)
(2370, 1827)
(2370, 1828)
(2370, 1829)
(2370, 1830)
(2370, 1831)
(2370, 1832)
(2370, 1833)
(2370, 1834)
(2370, 1835)
(2370, 1836)
(2370, 1837)
(2370, 1838)
(2370, 1839)
(2370, 1840)
(2370, 1841)
(2370, 1842)
(2370, 1843)
(2370, 1844)
(2370, 1845)
(2370, 1846)
(2370, 1847)
(2370, 1848)
(2370, 1849)
(2370, 1850)
(2370, 1851)
(2370, 1852)
(2370, 1853)
(2370, 1854)
(2370, 1855)
(2370, 1856)
(2370, 1857)
(2370, 1858)
(2370, 1859)
(2370, 1860)
(2370, 1861)
(2370, 1862)
(2370, 1863)
(2370, 1864)
(2370, 1865)
(2370, 1866)
(2370, 1867)

(67, 50)
(67, 51)
(67, 52)
(67, 53)
(67, 54)
(67, 55)
(67, 56)
(67, 57)
(67, 58)
(67, 59)
(67, 60)
(67, 61)
(67, 62)
(67, 63)
(67, 64)
(67, 65)
(67, 66)
Running cold
Running hot
Read cold and hot catalogs
['NUMBER', 'FLUX_ISO', 'FLUXERR_ISO', 'MAG_ISO', 'MAGERR_ISO', 'FLUX_AUTO', 'FLUXERR_AUTO', 'MAG_AUTO', 'MAGERR_AUTO', 'MAG_BEST', 'MAGERR_BEST', 'KRON_RADIUS', 'BACKGROUND', 'X_IMAGE', 'Y_IMAGE', 'ALPHA_J2000', 'DELTA_J2000', 'CXX_IMAGE', 'CYY_IMAGE', 'CXY_IMAGE', 'ELLIPTICITY', 'FWHM_IMAGE', 'FLUX_RADIUS', 'FLAGS', 'CLASS_STAR', 'A_IMAGE', 'B_IMAGE', 'XMIN_IMAGE', 'YMIN_IMAGE', 'XMAX_IMAGE', 'YMAX_IMAGE', 'ELONGATION', 'THETA_IMAGE', 'ISOAREA_IMAGE']
Including hot detections
('N:', 39, 0, 416)
('N:', 39, 1, 412)
('N:', 39, 2, 410)
('N:', 39, 3, 408)
('N:', 39, 4, 405)
('N:', 39, 5, 404)
('N:', 39, 6, 402)
('N:', 39, 7, 399)
('N:', 39, 8, 395)
('N:', 39, 9, 393)
('N:', 39, 10, 390)
('N:', 39, 11, 389)
('N:', 39, 12, 386)
('N:', 39, 13, 384)
('N:', 39, 14, 383)
('N:', 39, 15, 381)
('N

In [20]:
 if len(idx_c) > 1 and len(cold_table['KRON_RADIUS'][idx_c]) > 0:
            cold_table['KRON_RADIUS'][idx_c] = np.median(cold_table['KRON_RADIUS'])

In [23]:
cold_table

array((1., 13.15563, 2.566713, 23.2522, 0.2119, 104.1275, 7.228564, 21.0061, 0.0754, 21.0061, 0.0754, 8.82, 0.09747316, 1099.4043, 326.8728, 11.2180455, 41.6562863, 0.96399647, 0.6317324, -0.20099126, 0.22, 6.79, 2.977, 0., 0.759, 1.287, 1.004, 1098., 325., 1101., 329., 1.282, 74.41, 17.),
      dtype=[('NUMBER', '<f8'), ('FLUX_ISO', '<f8'), ('FLUXERR_ISO', '<f8'), ('MAG_ISO', '<f8'), ('MAGERR_ISO', '<f8'), ('FLUX_AUTO', '<f8'), ('FLUXERR_AUTO', '<f8'), ('MAG_AUTO', '<f8'), ('MAGERR_AUTO', '<f8'), ('MAG_BEST', '<f8'), ('MAGERR_BEST', '<f8'), ('KRON_RADIUS', '<f8'), ('BACKGROUND', '<f8'), ('X_IMAGE', '<f8'), ('Y_IMAGE', '<f8'), ('ALPHA_J2000', '<f8'), ('DELTA_J2000', '<f8'), ('CXX_IMAGE', '<f8'), ('CYY_IMAGE', '<f8'), ('CXY_IMAGE', '<f8'), ('ELLIPTICITY', '<f8'), ('FWHM_IMAGE', '<f8'), ('FLUX_RADIUS', '<f8'), ('FLAGS', '<f8'), ('CLASS_STAR', '<f8'), ('A_IMAGE', '<f8'), ('B_IMAGE', '<f8'), ('XMIN_IMAGE', '<f8'), ('YMIN_IMAGE', '<f8'), ('XMAX_IMAGE', '<f8'), ('YMAX_IMAGE', '<f8'), ('ELONG

In [78]:
len(table_allll)

1622

In [1]:
import numpy as np

# Set up matplotlib
import matplotlib.pyplot as plt
import os
from astropy.io import fits

In [11]:
data_path, res_path = './data/', './res_test/'

0

In [23]:
os.system('cd '+data_path+'; astcrop --section=10:4157,40:2148 --mode=img --hdu=1 hlsp_phat_hst_acs-wfc_12057-m31-b09-f01_f475w_v1_drz.fits')

0

In [27]:
hdu_list = fits.open('./data/ds9b09f01f475chip1.fits')
hdu_list.info()

Filename: ./data/ds9b09f01f475chip1.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      69   (4148, 2109)   float32   


In [44]:
2109-58.75

2050.25

In [41]:
hdu_list = fits.open('./data/ds9b09f01f475w7.fits')
hdu_list.info()

Filename: ./data/ds9b09f01f475w7.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      25   (1295, 470)   float32   


In [21]:
hdu_list = fits.open('./data/dsB09F01-3.0_drz.fits')
hdu_list.info()

Filename: ./data/dsB09F01-3.0_drz.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      25   (1295, 470)   float32   


In [22]:
print(hdu_list[0].data)

[[0.24386056 0.24386056 0.24386056 ... 0.12969033 0.12969033 0.12969033]
 [0.24386056 0.24386056 0.24386056 ... 0.12969033 0.12969033 0.12969033]
 [0.24386056 0.24386056 0.24386056 ... 0.12969033 0.12969033 0.12969033]
 ...
 [0.10237297 0.10237297 0.10237297 ... 0.18251471 0.18251471 0.18251471]
 [0.10237297 0.10237297 0.10237297 ... 0.18251471 0.18251471 0.18251471]
 [0.09868278 0.09868278 0.09868278 ... 0.11969352 0.11969352 0.11969352]]


In [23]:
hdu_list = fits.open('./data/hlsp_phat_hst_acs-wfc_12057-m31-b09-f01_f475w_v1_drz.fits')
hdu_list.info()

Filename: ./data/hlsp_phat_hst_acs-wfc_12057-m31-b09-f01_f475w_v1_drz.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     489   ()      
  1  SCI           1 ImageHDU       143   (4217, 4243)   float32   
  2  WHT           1 ImageHDU       150   (4217, 4243)   float32   
  3  CTX           1 ImageHDU       150   (4217, 4243)   int32   


In [143]:
import os
res_path = './res_test/'
pref = 'hlsp_phat_hst_acs-wfc_12057-m31-b09-f01_f475w_v1_'
outcat = res_path+pref+'hot.cat'

In [144]:
reg1 = res_path + 'test_f475w3.0.reg'
reg2 = res_path + 'test_f475w4.0.reg'
os.system("awk '{print \"ellipse(\"$14\",\"$15\",\"($26*$12)\",\"($27*$12)\",\"$33\")\"}' "+outcat+ " > " + reg1)
os.system("awk '{print $16,$17}' "+outcat+ " > " + reg2)

0

In [37]:
os.system('cd '+data_path+'; ds9 -zoom to fit ds9b09f01f475chip1.fits -saveimage ds9b09f01f475w5.fits -exit') 

0

In [40]:
os.system('cd '+data_path+'; ds9 -width 1360 -height 768  hlsp_phat_hst_acs-wfc_12057-m31-b09-f01_f475w_v1_drz.fits -zoom 4 -pan 161.875 58.75 image -saveimage ds9b09f01f475w7.fits -exit')

0

In [51]:
323.75*2+161.875

809.375

In [54]:
58.75+117.5*2

293.75

In [55]:
x = np.arange(58.75,293.75,117.5)

In [57]:
print('x[1]')

x[1]


In [48]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [6]:
data_path, res_path = './data/', './res_test/'  
X = np.arange(161.875,809.375,323.75)
Y = np.arange(58.75,293.75,117.5)
N = 0
table_alll = []
outcat = res_path+'ds9b09f01f475w_comb.cat'
for p in range(len(Y)):
    for q in range(len(X)):
        x = X[q]
        y = Y[p]
        n = str(N)
        os.system('cd '+data_path+'; ds9 -width 1360 -height 768 ds9b09f01f475chip1.fits -zoom 4 -pan to %f %f image -saveimage ds9b09f01f475w%s.fits -exit' %(x,y,n))
        N = N+1

In [103]:
os.system('cd '+data_path+'; ds9 -width 1360 -height 768 hlsp_phat_hst_acs-wfc_12057-m31-b09-f01_f475w_v1_drz.fits -zoom 4 -pan to '60 + 'image'+' -saveimage ds9b09f01f475w'+'1'+'.fits -exit')

SyntaxError: invalid syntax (<ipython-input-103-35f54b6257e2>, line 1)

In [8]:
b = [0,1,2,3]
print(range(1,len(b)))

[1, 2, 3]


In [3]:
run run_cold+hot_f475w_Nie_20201022.py

Running cold
Running hot
Read cold and hot catalogs
['NUMBER', 'FLUX_ISO', 'FLUXERR_ISO', 'MAG_ISO', 'MAGERR_ISO', 'FLUX_AUTO', 'FLUXERR_AUTO', 'MAG_AUTO', 'MAGERR_AUTO', 'MAG_BEST', 'MAGERR_BEST', 'KRON_RADIUS', 'BACKGROUND', 'X_IMAGE', 'Y_IMAGE', 'ALPHA_J2000', 'DELTA_J2000', 'CXX_IMAGE', 'CYY_IMAGE', 'CXY_IMAGE', 'ELLIPTICITY', 'FWHM_IMAGE', 'FLUX_RADIUS', 'FLAGS', 'CLASS_STAR', 'A_IMAGE', 'B_IMAGE', 'XMIN_IMAGE', 'YMIN_IMAGE', 'XMAX_IMAGE', 'YMAX_IMAGE', 'ELONGATION', 'THETA_IMAGE', 'ISOAREA_IMAGE']
Including hot detections
('N:', 99, 0, 2602)
('N:', 99, 1, 2600)
('N:', 99, 2, 2599)
('N:', 99, 3, 2598)
('N:', 99, 4, 2597)
('N:', 99, 5, 2595)
('N:', 99, 6, 2594)
('N:', 99, 7, 2593)
('N:', 99, 8, 2589)
('N:', 99, 9, 2588)
('N:', 99, 10, 2587)
('N:', 99, 11, 2584)
('N:', 99, 12, 2583)
('N:', 99, 13, 2582)
('N:', 99, 14, 2577)
('N:', 99, 15, 2576)
('N:', 99, 16, 2575)
('N:', 99, 17, 2574)
('N:', 99, 18, 2572)
('N:', 99, 19, 2571)
('N:', 99, 20, 2570)
('N:', 99, 21, 2569)
('N:', 99, 22,

(2448, 487)
(2448, 488)
(2448, 489)
(2448, 490)
(2448, 491)
(2448, 492)
(2448, 493)
(2448, 494)
(2448, 495)
(2448, 496)
(2448, 497)
(2448, 498)
(2448, 499)
(2448, 500)
(2448, 501)
(2448, 502)
(2448, 503)
(2448, 504)
(2448, 505)
(2448, 506)
(2448, 507)
(2448, 508)
(2448, 509)
(2448, 510)
(2448, 511)
(2448, 512)
(2448, 513)
(2448, 514)
(2448, 515)
(2448, 516)
(2448, 517)
(2448, 518)
(2448, 519)
(2448, 520)
(2448, 521)
(2448, 522)
(2448, 523)
(2448, 524)
(2448, 525)
(2448, 526)
(2448, 527)
(2448, 528)
(2448, 529)
(2448, 530)
(2448, 531)
(2448, 532)
(2448, 533)
(2448, 534)
(2448, 535)
(2448, 536)
(2448, 537)
(2448, 538)
(2448, 539)
(2448, 540)
(2448, 541)
(2448, 542)
(2448, 543)
(2448, 544)
(2448, 545)
(2448, 546)
(2448, 547)
(2448, 548)
(2448, 549)
(2448, 550)
(2448, 551)
(2448, 552)
(2448, 553)
(2448, 554)
(2448, 555)
(2448, 556)
(2448, 557)
(2448, 558)
(2448, 559)
(2448, 560)
(2448, 561)
(2448, 562)
(2448, 563)
(2448, 564)
(2448, 565)
(2448, 566)
(2448, 567)
(2448, 568)
(2448, 569)
(244

(2448, 1206)
(2448, 1207)
(2448, 1208)
(2448, 1209)
(2448, 1210)
(2448, 1211)
(2448, 1212)
(2448, 1213)
(2448, 1214)
(2448, 1215)
(2448, 1216)
(2448, 1217)
(2448, 1218)
(2448, 1219)
(2448, 1220)
(2448, 1221)
(2448, 1222)
(2448, 1223)
(2448, 1224)
(2448, 1225)
(2448, 1226)
(2448, 1227)
(2448, 1228)
(2448, 1229)
(2448, 1230)
(2448, 1231)
(2448, 1232)
(2448, 1233)
(2448, 1234)
(2448, 1235)
(2448, 1236)
(2448, 1237)
(2448, 1238)
(2448, 1239)
(2448, 1240)
(2448, 1241)
(2448, 1242)
(2448, 1243)
(2448, 1244)
(2448, 1245)
(2448, 1246)
(2448, 1247)
(2448, 1248)
(2448, 1249)
(2448, 1250)
(2448, 1251)
(2448, 1252)
(2448, 1253)
(2448, 1254)
(2448, 1255)
(2448, 1256)
(2448, 1257)
(2448, 1258)
(2448, 1259)
(2448, 1260)
(2448, 1261)
(2448, 1262)
(2448, 1263)
(2448, 1264)
(2448, 1265)
(2448, 1266)
(2448, 1267)
(2448, 1268)
(2448, 1269)
(2448, 1270)
(2448, 1271)
(2448, 1272)
(2448, 1273)
(2448, 1274)
(2448, 1275)
(2448, 1276)
(2448, 1277)
(2448, 1278)
(2448, 1279)
(2448, 1280)
(2448, 1281)
(2448, 1282)

(2448, 1861)
(2448, 1862)
(2448, 1863)
(2448, 1864)
(2448, 1865)
(2448, 1866)
(2448, 1867)
(2448, 1868)
(2448, 1869)
(2448, 1870)
(2448, 1871)
(2448, 1872)
(2448, 1873)
(2448, 1874)
(2448, 1875)
(2448, 1876)
(2448, 1877)
(2448, 1878)
(2448, 1879)
(2448, 1880)
(2448, 1881)
(2448, 1882)
(2448, 1883)
(2448, 1884)
(2448, 1885)
(2448, 1886)
(2448, 1887)
(2448, 1888)
(2448, 1889)
(2448, 1890)
(2448, 1891)
(2448, 1892)
(2448, 1893)
(2448, 1894)
(2448, 1895)
(2448, 1896)
(2448, 1897)
(2448, 1898)
(2448, 1899)
(2448, 1900)
(2448, 1901)
(2448, 1902)
(2448, 1903)
(2448, 1904)
(2448, 1905)
(2448, 1906)
(2448, 1907)
(2448, 1908)
(2448, 1909)
(2448, 1910)
(2448, 1911)
(2448, 1912)
(2448, 1913)
(2448, 1914)
(2448, 1915)
(2448, 1916)
(2448, 1917)
(2448, 1918)
(2448, 1919)
(2448, 1920)
(2448, 1921)
(2448, 1922)
(2448, 1923)
(2448, 1924)
(2448, 1925)
(2448, 1926)
(2448, 1927)
(2448, 1928)
(2448, 1929)
(2448, 1930)
(2448, 1931)
(2448, 1932)
(2448, 1933)
(2448, 1934)
(2448, 1935)
(2448, 1936)
(2448, 1937)